### ISSUE TITLE
Foreign function call with missing return type is not caugh by type checker, but causes shouldnt error

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#113]
For example, the code:

pub def =(x:string, y:string):bool  = foreign c strcmp(x,y) = 0

should trigger a type error, but instead causes a shouldnt

**Comment by 09milk** [comment]
is this fixed/changed? I tested this in the newest compiler version and my code give neither "shouldnt" nor "type error", it just compile successfully.

Code:
```
def myeq(x:string, y:string):bool = foreign c strcmp(x,y) = 0

!println(myeq("hello world!","123"))
```

**Comment by pschachte** [comment]
Yep, you're right!  Thanks for catching that.
