### ISSUE TITLE
`foreign lpvm alloc` only supports `int` constant size

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#145]
The following code should compile, however does not.

```
def {noinline, semipure} foo(size:int) {
    foreign lpvm {impure} alloc(size, ?mem:machine_word)
}
```

Instead, the following error message is produced:
```
src/AliasAnalysis.hs:654:9-42: Non-exhaustive patterns in [ArgInt size _, struct]
```

**Comment by CaviarChen** [comment]
Right, that part of code is related to the dead memory cell reusing. At the time we implemented that, we only allowing calling alloc with constant size. 

A easy fix could be just ignoring the variable size case. 

I think there was a discussion about supporting a subset of the variable size case for immutable array, but I don't know how that went. In general, the dead memory cell reusing doesn't need to know the actual size of a cell in compile time, all it needs is whether two cells have the same size.

**Comment by jimbxb** [comment]
I am going to close this issue as I believe is now resolved.
