### ISSUE TITLE
Backticks are too powerful

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#157]
```
def `a really long ident that shouldnt be a thing` = 1
def `a $ sign :)` = 1
```

Should be illegal, yet is tokenised just fine

I think for now disallowing spaces/newlines should be best

**Comment by pschachte** [comment]
Why do you think it should not be allowed to include special characters in backquoted identifiers?

I did think about this when I implemented the backquote thing and decided to allow any string to be an identifier until I saw a reason to forbid it.  Currently, allowing $ in identifiers could be problematic, but it's not possible to use a backquote in a backquoted identifier, so we could switch from $ to ` in generated names.

There's probably a strong argument to forbid a newline or any other control characters in identifiers, which I think I didn't do.  Do you see a reason to forbid other characters?

**Comment by jimbxb** [comment]
The main issue I saw was using `$`, as we do use that for behind the scenes things. Changing to `` ` `` might solve this, as you suggest.

The other issue was allowing newlines, which I didn't spell out in the examples shown, as with other control characters as you mentioned. 

Tabs could also cause issues (for the programmer) where they appear to look like a space, or vis versa. I suppose we could allow a space but not a tab, or further not allow both.

Other than that, I don't think there's much of an issue beyond aesthetics, so perhaps I should adopt your approach of "it's okay until it's not okay" on this one.
