### ISSUE TITLE
Update LPVM implementation to allow forks on non-Boolean variables.  Should generate LLVM computed goto.

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#161]
The LPVM design allows forks on non-Boolean variables, but it's not yet implemented.

We may want to add an extra argument to forks to hold the guaranteed greatest possible value for the variable.

**Comment by jimbxb** [comment]
LLVM supports a `switch` statement that I believe fits our use case well.

Documentation can be found here: https://llvm.org/docs/LangRef.html#switch-instruction

**Comment by jimbxb** [comment]
As noted in #297 

While we can now generate valid LLVM for n>3-ary branches, there is no transformation of LPVM to actually generate these branches
