### ISSUE TITLE
Change the notation for type variables

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#166]
Currently the notation for type variables makes use of a preceding `?`, which of course is used to denote outward flow also. 

In some situations (such as a higher order types declaration), where types and flows must be handled in tandem, the notation become confusing: is `?a` an outflowing value of type `a` or is an inflowing value of type `?a`.

On solution to this is to use a `:` separator to disambiguate these cases.

Alternatively, we can change the prefix symbol for type variables. One possibility is to follow other languages that use a `'`, but this may be confused in the scanner for a character quote. Else we could use a `^` as this would be unused (yet reserved) in this context. I'm in favour of the `^`

**Comment by pschachte** [comment]
How about defining a type variable as a single upper case letter followed by 0 or more digits?  The forbid type names of that form.  That has the advantage of following common conventions for type variables, and not requiring any special prefix symbol.  

Another option would be to explicitly "quantify" type variables.  That already happens in type declarations, where type variables appearing in the type definiton must appear as parameters of the type being defined.  We could provide a syntax for quantifying and scoping a type variable in other contexts, such as proc declarations.

**Comment by jimbxb** [comment]
After further discussion the resolution of this will be to use `[A-Z]\d*` (single uppercase followed by digits) as previously suggested.
