### ISSUE TITLE
Make module names that look like type variables illegal

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#190]
Following from #166, trying to compile module name of the form `[A-Z][0-9]*` should result in an error.

**Comment by pschachte** [comment]
Closed by #351.  Doesn't make it illegal, just a warning, but I think that's good enough.

**Comment by jimbxb** [comment]
@pschachte are you sure?

**Comment by pschachte** [comment]
No, you were right, you can still compile a module T.wybe.  Will fix.

**Comment by pschachte** [comment]
Actually `type T` won't parse, because it expects a `moduleName`, which specifically excludes `isTypeVar`, so that's OK (though the error message just says `Syntax error: unexpected identifier T`).
