### ISSUE TITLE
--no-llvm-opt flag is never used

### ISSUE THREAD

**Issue by neon64** [pschachte/wybe#266]
As part of working on https://github.com/pschachte/wybe/issues/109, I've found it useful to sometimes dump LLVM IR to a file.
By default however, I believe `wybemk` writes optimized LLVM IR. Although the `--no-llvm-opt` flag exists, it doesn't control anything (searching the code: https://github.com/pschachte/wybe/search?q=optNoLLVMOpt)

I've got a quick fix on my current dev branch: https://github.com/neon64/wybe/blob/d94021a424706c43ddadbc418f443676381f0b36/src/Emit.hs#L112-L121. Hopefully tomorrow or so I can make a separate branch just containing that fix, and submit a PR.

**Comment by jimbxb** [comment]
Hi Chris!

Perhaps we should use `withModule` instead of `withContext` as this would reduce some code duplication. 

Unless you want to force it to not verify the LLVM, which you could just pass in `False` for if that's a requirement?
