### ISSUE TITLE
Extend the standard library with higher order procedures

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#280]
As the title says.

Open to more suggestions, but implementations of `map`, `fold`, and `filter` are likely good starting points

Common predicates will also be useful, such as `const` and `id`

**Comment by jimbxb** [comment]
This issue may not truly be closed -- see #281

**Comment by pschachte** [comment]
An issue like this is pretty open-ended; it'll never be truly satisfied.  But I think it's OK to close it.
