### ISSUE TITLE
Move the `print` (and other I/O) procedures into their respective type's module.

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#286]
As the title says.

I find when there is some issue with resolving overloading, especially with the `print` procedure, that the error messages are needlessly bad. As all `print` procs are in `io`, they are distinguished only by their indexed name (`wybe.io.print<0>`). Moving each procedure into the respective module allows for the error message to be slightly more comprehensible, being qualified by their type's module name.

This also would allow the programmer to say `int.print` instead of relying on a type constraint if all else failed.

**Comment by pschachte** [comment]
Good idea.

Longer term, I'd like to print everything by first converting to a string, but until then, moving the print procs into the module of the thing to be printed makes good sense.
