### ISSUE TITLE
LLVM pretty-printed by `ASTShow.hs` differs from LLVM written by `Emit.hs`

### ISSUE THREAD

**Issue by neon64** [pschachte/wybe#288]
Just noticed yesterday that copy-pasting the LLVM printed in the final-dump test cases didn't compile in godbolt, e.g.: https://godbolt.org/z/714bo13zz

It seems like the main difference is that the actual generated LLVM code (`type_generics.ll`) restarts temporaries at `%0` at the start of every function, whereas the pretty-printed LLVM (`type_generics.exp`) starts at `%1` and keeps increasing throughout the whole file.

Here's a brief example of the slight differences:
![image](https://user-images.githubusercontent.com/7961339/167066785-87a3e538-f7dd-4ed9-9e28-1ea6d7d1a549.png)

The language reference says the following (which backs up the compile errors in godbolt) 
> Unnamed temporaries are numbered sequentially (using a per-function incrementing counter, starting with 0). Note that basic blocks and unnamed function parameters are included in this numbering. For example, if the entry basic block is not given a label name and all function parameters are named, then it will get number 0.

I guess it doesn't matter if the FinalDump LLVM is accepted by LLVM or not, but it seems a little fishy that it should be so different from the LLVM we actually produce. I think the reason for the difference is that `ASTShow.hs` uses https://github.com/llvm-hs/llvm-hs-pretty to do LLVM IR pretty-printing, whereas `Emit.hs` uses `writeLLVMAssemblyToFile` which uses the actual LLVM implementation. I've tested fixing `ASTShow.hs` by switching to use `LLVM.moduleLLVMAssembly` instead. The downside is that it requires an LLVM context (thus inside `IO` monad), thus `Module` cannot implement `Show` anymore.

One benefit to changing the final dump LLVM IR to match the emitted `.ll` files (apart from consistency), is that since unnamed temporaries would restart at %0 each function, the changes to final-dump outputs would become less noisy, e.g.: this example where some of the diff is just renaming from `%70` to `%71` and onwards, obscuring the real changes.

![image](https://user-images.githubusercontent.com/7961339/167067708-3453c39e-7ae1-468b-ad41-26e322a08c75.png)

**Comment by jimbxb** [comment]
I like the idea of starting from `%0` for the temporary registers. 

I'm not sure losing the ability to `show` a Module is a great benefit overall though.
