### ISSUE TITLE
wybemk is unable to locate cbits.so

### ISSUE THREAD

**Issue by CaviarChen** [pschachte/wybe#3]
In the current makefile, it will build the wybemk and copy it to "~/.local/bin". However, the cbits.so is built and put in the wybe project folder. 
When using wybemk to compile a program, it seems that the wybemk will try to locate the cbits.so in the work directory and throw an internal error "clang: error: no such file or directory: 'cbits.so'".

The compiler is also trying to use the "./wybelibs/wybe.wybe" in the current work directory.

**Comment by pschachte** [comment]
Fixed.   Now wybe and its library can be installed wherever they are configured, and the compiler will link correctly.
