### ISSUE TITLE
Add set of optimisations, and derive flags to enable/disable them

### ISSUE THREAD

**Issue by neon64** [pschachte/wybe#309]
From https://github.com/pschachte/wybe/pull/305

> James's suggestion is a good one. Except rather than naming all the optimisation options "No"Something, they should just be named after the feature, and there should be a default set of optimisations. Then the option parser should understand that options that begin with "no-" mean to turn off the optimisation with the "no-" stripped off. That would let us add some optimisations that are not enabled by default.

Something like:

```
data Options = Options {
    -- ...
    , optOptFlags = Set OptFlag
    -- 
    }
    
data OptFlag = MultiSpecz | TailCallModCons | LlvmOpt
   deriving (Eq, Ord, Enum, Bounded)
```

all three of these would be enabled by default, in line with existing behaviour

I'm happy to implement this soon, I've just promised myself to focus more on report/presentation this week.

**Comment by jimbxb** [comment]
I have a free afternoon and am happy to tackle this.
