### ISSUE TITLE
Support multiple specialisation

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#31]
This allows generation of specialised versions of procedures based on how it will be called, and allows the compiler to select the best available version of a procedure for each call.

**Comment by CaviarChen** [comment]
- [ ] refactor `SpeczVersionId ` and `AliasMultiSpeczInfo `. More detail can be found in the comments of https://github.com/pschachte/wybe/pull/35

**Comment by pschachte** [comment]
Is it time to close this issue now (and open new ones for any unfinished aspects of this)?

**Comment by CaviarChen** [comment]
Sure.
