### ISSUE TITLE
Misleading error when trying to bind variable without `?`

### ISSUE THREAD

**Issue by neon64** [pschachte/wybe#310]
The following minimal example:

```
def increment(!x: int) {
    ?x = x+1
}

l = 1
increment(!l)
```

yields the following error:

```
Error detected during type checking of module(s) undeclared_variable
testing/undeclared_variable.wybe:6:1: Type error in call to increment, argument 1
```

whereas I believe the actual underlying issue is that `l` hasn't been bound yet (because I mistakenly wrote `l=1` instead of `?l = 1`.

Doing the same without the implicit `inout` flow yields a helpful error about `l` not being defined, as expected.

```
def increment(x: int, ?x2: int) {
    ?x2 = x+1
}

l = 1
increment(l, ?l2)
!println(l2)
```

```
Error detected during type checking of module(s) undeclared_variable
testing/undeclared_variable.wybe:5:1: 'l' unknown in module top-level code
testing/undeclared_variable.wybe:6:11: 'l' unknown in module top-level code
```

On a related note, as an extension it would be nice to provide hints to the user on how to fix common mistakes such as the "trying to assign using `l=1` mistake" (these error hints are something that rustc does very well - might be good inspiration)

```
testing/undeclared_variable.wybe:5:1: 'l' unknown in module top-level code
                                                             note: perhaps you meant to assign to `l` with `?l = 1` instead?
```

**Comment by jimbxb** [comment]
My suspicion on this is a remnant from my patch of delaying the assignment transformation into type checking. I believe the type inference part assumes that the flows must be in and out or out and in, leading to the issue.

**Comment by jimbxb** [comment]
Okay, so this one seems a little deeper rooted than I thought.

Here is the key part from the type dump

```
Types: module top-level code > public {impure} (0 calls)
Types: 4: () use !wybe.io.io:
Types:     i(?tmp#0 @opt:5:1)
Types:     =(tmp#0, 1 @opt:5:5)
Types:     increment(!i @opt:6:6)
```

As you can see, the `i = 1` is recognised as a call to `i`, and as that is assigned somewhere in the body of the proc (really, re-assigned), the call is inferred to be a HO call.
