### ISSUE TITLE
Add an LPVM construct to subvert some pure procedures from being removed.

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#325]
This came up in an older rendition of global variables wherein I had an LPVM `void` instruction that existed solely to avoid a pure call from being omitted, assuming it is marked as being `semipure`/`impure`.

I.e., something like the following

```
complex_computation(?x)
foreign lpvm {impure} void(x)
```

This would force the compiler to produce a program that does said `complex_computation` without having to make the `complex_computation` impure. We shouldn't explicitly generate the `void` instruction when translating to LPVM, as its just a dummy (perhaps the right name to use is `phantom` :-) ).

I could see this being useful in the benchmarking module (#304), as you may want to benchmark a procedure that returns something but don't care about the returned value. The LLVM compiler might have something to say about removing the call, but I suspect it will be okay

**Comment by jimbxb** [comment]
This should be fixed now as of #333 and the example of `need` in `test-cases/final-dump/need.wybe`. However, simple closures dont allow a simple fix to this problem as seen in `test-cases/final-dump/higher_order_impure.wybe`. This means that a call like `!need {impure}{ _ = this }` wont actually keep `this` around due to the optimisation of `move` in `impure` contexts. 

@pschachte thoughts

**Comment by pschachte** [comment]
My reasoning for continuing to allow LPVM optimisation of low level instructions in impure code is that for the most part, those instructions are not written by the user, so the user wouldn't really think of them at all and would not expect them to be left unchanged.  The the one exception to this is the `=` proc, which is compiled into either a `foreign llvm move` instruction or into a function call.  In the latter case, the call will not be optimised away, leaving only the case of *variable* `=` *variable* as normal user code that will be optimised even in an impure proc body.  So the `test-cases/final-dump/higher_order_impure.wybe` example is a very narrow exception to the rule that normal code in an impure body won't be optimised away.  This could be fixed, but I'm not sure it's worth it.  So I agree we should close this issue.
