### ISSUE TITLE
Impure procs should not be inlined unless explicitly marked for inlining

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#332]
... because inlining loses impurity information.

For example

```
def {impure} impure {foreign c {impure} printf(c"Hello, World!\n")}

!impure # shouldn't be inlined
```

**Comment by jimbxb** [comment]
I think we can do better than this. It shouldn't hurt to inline a proc if the purity of the callee is no greater than the caller. I.e. inlining a pure proc in a semi pure context is okay, as is inlining an impure proc in an impure context.

So perhaps we could add another level of inlining, where if inlining is inferred we can only inline if the purity of the callee is no greater.

**Comment by pschachte** [comment]
This will still inline calls to procs that have been marked for inlining.  This change also allows impure procs to be explicitly marked for inlining, it just doesn't apply inlining heuristics to impure procs.

You've actually mentioned exactly the case I don't want optimised:  I want to be able to stop a call to a pure proc where the output is unused from being optimised away if the call appears in impure code.  I suppose impure code could treat different optimisations differently, eg inlining pure calls but not eliminating, but that seems complicated.  I was already leaning toward using all the normal optimisations for foreign (llvm) instructions, but not for wybe calls.  But I don't want this to be too complex for users.  I'm thinking you can always make a small proc impure and inlined, and use it in a larger pure proc, to get fine control over disabling optimisation.

Longer term, it'd be nice to be able to write something like
```
stmt(...)
stmt(...)
{impure}{not_to_be_optimised(...)}
stmt(...)
```

**Comment by jimbxb** [comment]
I fail to see why applying the heuristics to impure procs is a problem. 

With the "inferred inline" inlining level, any heuristically inferred inlining would be marked with that level, which is distinct from the explicit inlining level. Then, if you're in say a pure body and you're considering inlining a proc, you can only inline if it is explicitly marked for inlining or it has inferred inlining and pure. For semipure it's the same but instead of just pure it also considers semipure inferred-inline, and for impure it's also impure inferred-inline.

**Comment by pschachte** [comment]
It's not that auto-inlining is a problem, it's a matter of what `impure` means.  The idea is that it's telling the compiler that this code doesn't mean what the compiler would think it means if it were pure, so the compiler should be much more cautious when compiling it.  So I guess this comes down to a question of what damage is done by inlining an impure proc that the programmer hasn't said to inline.  If we're benchmarking to determine the cost of a wybe proc call, for example, then automatically inlining would defeat our purpose.

**Comment by pschachte** [comment]
OK, James has convinced me that it's enough for the bodies of impure procs not to be have calls optimised, and auto-inlining small impure procs is OK.  So I'm withdrawing this issue.
