### ISSUE TITLE
Can't compile simple resourceful HO function

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#342]
This code
```
def my_map(f:{resource}(T,?T), lst:list(T)):list(T) =
    if {
        lst = [?h|?t] :: [h2 | my_map(f, t)] where { !f(h, ?h2) }
    |   else          :: []
    }
```
Produces type errors for all three arguments to the output cons on the 3rd line.  If the `{resource}` modifier (and the `!` in front of the call to `f`) are removed, it compiles fine.

**Comment by jimbxb** [comment]
Ah, I see. It's an issue with partial application.

The call *should* have a `!` before it, but as it doesn't the call is considered a partial application of the `my_map` procedure, so `my_map(f, t):{resource}(?list(T))`.

I don't think that's what we want.

**Comment by jimbxb** [comment]
Another point to note is it isnt immediately clear what should come first--the `my_map` call or the `f` call. With resources, this matters

**Comment by pschachte** [comment]
Ah, you're right, I forgot a `!`.  I should have seen that.  So the code is erroneous, but the error message was not helpful.

I'm a bit confused about the partial application issue.  `my_map(f, t)` appears in an expression context, so we know it must have one more argument.  With that argument added, it's saturated, so it can't be a partial application.  Then it should be clear that the type and mode are correct, but it's missing the `!`.

The body of the `where` clause must always be executed before the expression, so the order of the two resourceful calls is unambiguous.

**Comment by jimbxb** [comment]
On partial application, I wanted to handle a certain case where a "saturated" call would actually be a partial application. This case was for `read`. The `read` function call is flattened into `read(?tmp)`, but that matches the interface of `read` exactly, we're just missing a `!`. So even if a call is saturated, if it should have a `!` and we dont have such, it can be considered a partial call

**Comment by pschachte** [comment]
A fully saturated call that we want to pass as a closure is a very special case.  I agree, it's something we want to support somehow.  But we might want to support it in a perfectly pure context, such as a call `ackermann(3,3)` (an extremely expensive call) that we only want to execute if we actually need it, or at precisely the moment we want to execute it (eg, for benchmarking), so I don't think using the purity marker to determine when to execute it is the right solution.

I've been thinking of supporting a `{lazy}` annotation before a parameter, meaning that the argument passed in that position should not be evaluated before calling that proc, but instead should be passed as a saturated closure.  If that argument is passed to another `{lazy}` parameter, it would be passed unexecuted, but the first place it is used as an argument in a non-`{lazy}` position, it would be executed, and the result would be passed.  I think this would be a nice way to implement, eg, the benchmarking library.

Would this give you what you're looking for with regard to a saturated `read`?

**Comment by jimbxb** [comment]
For the `read` case I want to do something like:

```
def readN(read:{resource}(?X), n:int):list(X) = ls where {
    ?ls = []
    for i in 0..n {
        !read(?x)
        ?ls = [x | ls]
    }
}

!readN(read, 10, ?ls:list(int))
```

I don't think laziness helps here because this parameter would get called multiple times with *different* behaviour.


```

**Comment by jimbxb** [comment]
I suppose we *could* make it such that a call can only be a saturated partial application iff the call uses some resource, not if it uses a resource or has a resourceful higher-order arg

**Comment by pschachte** [comment]
Yup, that is something different, and it only applies to non-pure or resourceful calls.  But given how easy it is to forget the `!` on a call, and how unhelpful the error message is when you do, I don't think using the omission of the `!` to distinguish between closure construction and execution is good.

I don't really understand what you're proposing now.   That error message looks good, but I'm not sure in which contexts the presence/absence of a `!` would determine whether something is a closure or an expression to be executed.

**Comment by pschachte** [comment]
Since an impure/resourceful expression only makes sense when there's only one in the statement, it might be better to forbid it altogether.

**Comment by jimbxb** [comment]
The context where something would be considered a partial application is where the call is not saturated, or where saturated if it uses some resource. The change modifies what "uses some reasouce" means, from "uses a resource or has a resourceful higher order argument" to "uses a resource"

**Comment by pschachte** [comment]
How would impurity figure into it?  Is a saturated impure call an expression or a closure?

Now that I think about it, any HO parameter type that has no inputs, but zero or more outputs, will always be saturated when passed.  Your read example is like that.  Can we use the callee type to decide how to interpret the call?

**Comment by jimbxb** [comment]
I have not considered impurity. I dont think I want to either, as the call doesnt have any "extra arguments" that would be there in the case of a resourceful call (if you consider resources as extra arguments) 

If the param type has more than one output then the call is already going to look like a partial application, so we only have to consider the case where there is zero or one outputs. We already only consider a call to be a partial application based on the flows of the caller, i.e., the last flow must be out, and if we add in the callee types they may not currently be resolved so I can foresee that leading to issues.

**Comment by pschachte** [comment]
Impurity is much like resourcefulness, and should probably be handled the same way.  In fact, I've been thinking that maybe there should only be a single annotation for HO code that means "either impure or resourceful", without distinguishing between the two.

**Comment by jimbxb** [comment]
I'm not sure I agree they should be treated the same. If we know which resources two resourceful calls use, assuming the global flows are distinct, we should be able to reorder such calls as the global variables manipulated will be distinct. Whereas for an impure call, we can't reorder them.

Note: if both calls have inwards-only flows for the same resource, they can probably be re-ordered also. This is because the value before and after each call is the same, so the order of such calls is irrelevant with respect to that resource.

**Comment by pschachte** [comment]
Here I'm just referring to HO types.  So say a HO parameter to a proc `foo` is declared as `p:{resourceful}(...)`.  Looking at the body of the proc, you see some calls to some procs, including a call to `p`.  What code reorganisations are you allowed to do to the body of `foo`?  If you change `resourceful` to `impure`, how does that change what you are allowed to do?

Where it does make a difference is in the annotations you need to place on `foo` itself, and that may kill the whole idea.  I'm not sure...

**Comment by jimbxb** [comment]
That's a good point. If you define the `p` to be resourceful, then the proc will have universal global flows. That means that at call sites, it will kill all known definitions of global vairables. If you declare it to be impure, and actuymakes calls to `p` inside the proc, the whole proc needs to be non-pure, which doesn't imply any global flows, and may be subject to different optimisations at the call site

**Comment by pschachte** [comment]
Yes, that's right, if `impure` and `resource` are merged, they `p` would have to be treated as being both, which I guess is the same as `resourceful` (aside from what it implies about the proc that calls it).

The point of doing that would be the same as the reason for having a single `{resource}` annotation instead of separately listing the resources and flows:  allowing HO code to be more polymorphic.  I'd like it to be possible to write a single version of the standard HO funcs and procs, and then strengthen multiple specialisation if necessary to improve performance for various cases.

**Comment by jimbxb** [comment]
There's another case to consider. If we can lower a HO call to a FO call, then we currently get more information about the global flows of that call, which is different in the case it's impure. For instance, say that there's only inwards global flows and no needed outputs. If the call is impure, that cant get omitted.

**Comment by pschachte** [comment]
I think a HO type should be considered to specify an upper bound on the impurity/resourcefulness of the proc that can be provided as value for that argument.  If you know the actual value when compiling the proc, e.g. due to specialisation, then you can use the actual impurity/resourcefulness.  So I don't think that case is an argument against merging impurity and resourcefulness for HO types.  If you write a version of map that takes an impure/resourceful proc as argument, for example, you could generate a specialisation for the case that a pure proc is passed, and another for an impure, resourceless proc, and another for a resourceful (whether pure or impure) proc (that's the most general one, which would work for anything).  You could even generate specialised versions for particular HO arguments, in which case the specialisaiton will know which resources need to be flushed, so that a specialisation to map (*2) over a list wouldn't flush any resources to global, while one to map `print` over a list would only need to flush the `io` resource (which is to say, no actual values) to globals.
