### ISSUE TITLE
Incorporate parameter information in global flows

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#376]
Currently, the analysis of global flows for higher order calls is extremely conservative. That is, either all global's flow in and out of a higher order call or none do. This represents some issues where a global variable isn't actually modified through a higher order call.

Consider the following:

```
def {noinline} do(f:{resource}()) {
    !f
}

resource res:int = 0

?res = 1
!do {resource}{ pass }
!print res
```
This code is effectively the following in LPVM
```
def {noinline} do(f:{resource}())<univ, univ>:
    f

def anon()<{}, {}>:
    pass

foreign lpvm store(1, <<res>>)
do(anon)<univ, univ>
foreign lpvm load(<<res>>, ?res)
print(res)<{io}, {io}>
```

The `<univ, univ>` global flows are here because we don't know what global variables the resourceful HO call could touch, so we must assume all are. But, we do -- it is whatever the global flows are of the `f` parameter.

With the knowledge of the global flows of what is passed in at the call site of `do`, we should be able to remove the `load` instruction. Modifying the global flows of `do` to be `<{}, {}, {f}>` (no first order flows + flows of `f`), the call site call can be inferred to have no global flows. (This also proves that this `do` call has no effects and can be removed!)

The code would then be optimised into;
```
def {noinline} do(f:{resource}())<{}, {}, {f}>:
    f

def anon()<{}, {}, {}>:
    pass

foreign lpvm store(1, <<res>>)
print(1)<{io}, {io}, {}>
```

In essence, the global flows of a procedure would have to include the first order global flows, *and* the global flows of the arguments, if called. Special care would have to be taken when calling a non-parameter, but I believe the global flows of a local variable can be restricted to a set of parameter's global flows (or fall back to the universal set).

This analysis is only useful at the call site, not inside the body. This is still beneficial, I believe. Think at the callsite of a resourceful `map`

**Comment by jimbxb** [comment]
The global flows of parameters are probably best described by an integer, denoting the index of the parameter. This way, the integer can be used to on the caller side, indexing the arguments.

The global flows of a body would be as it now, being the union of all global flows across each prim. The global flows of each prim would have to be refined.

In order to capture the flow of parameters through the body, the flow of each variable must be captured. For inwards flowing parameters, the flow would be defined as `<{}, {}, {`*idx*`}`. Each variable defined somewhere in the body would then be defined as having the global flows of the *union* of the global flows of the prims that defined the variable. 

For instance, if we had some body as follows:

```
def foo(p0:{resource}(), p1:{resource}(), ?p2:{resource}(), b:bool)<{}, {}, {}>:
    case b:
    0:
         foreign llvm move(p0, ?p2)
    1:
         foreign llvm move(p1, ?p2)
```
The global flows of the `p2` variable could have the flows of `p0` (`<{}, {}, {0}>`) or `p1` (`<{}, {}, {0}>`), and as such can be inferred to have global flow `<{}, {}, {0, 1}>`. 

For LPVM prims, the flows can remain unchanged. For first order proc calls, the global flows would be the global flows of the proc in union with the global flows of the *in* flowing arguments. The higher order prim would be similar, however would use the global flow of the called term.

With the above proc, there are no global flows throughout the whole body due to there being no resourceful calls.

**Comment by pschachte** [comment]
Yes, good idea.

As a first approximation, can't we just assume that all HO arguments to a proc call are eventually called, so all flows of all HO arguments should be in the set?

**Comment by jimbxb** [comment]
Yes, as a first approximation it would be as such. Further calls to the body builder, or wherever this is placed, could further refine this information.

**Comment by jimbxb** [comment]
In implementing this, I've come across a case that I'd like to handle regarding generic types. Consider the following:

```
def {noinline} move(x:T, ?y:T)<{}, {}, {}>:
    foreign llvm move (x, ?y)

move(foo:{resource}(), ?f)
f()
```

We should expect `f` to have the same flows as whatever `foo` has. However, if we only track the flows of resourceful higher order terms then we would infer that this term has no flows. We could say that, because the type of `f` is not the same as the type of `y` (in `move`) that it could have universal flows. 

We can, however, do better, though it involves tracking the flows of generic types also. Generic types are the only instance where this could occur, and a generic type can never be called, so tracking these "flows" are never going to impact the flows of the procedure at hand. As such, we can analyse `move` with the following flows:

```
def {noinline} move(x:T <{}, {}, {0}>, ?y:T <{}, {}, {0}>)<{}, {}, {}>:
    foreign llvm move (x, ?y)
```
