### ISSUE TITLE
`save-state` usage warning in CI

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#378]
`save-state` is deprecated and will be disabled soon, according to a warning in the CI. We should probably fix that

See [here](https://github.com/pschachte/wybe/actions/runs/4089966536/jobs/7053054595) in the cache* steps

I think this might also be the reason the cache steps are running at all. I am not sure.

**Comment by pschachte** [comment]
Yikes!  Does that mean every test build during a CI will need to be from scratch?

**Comment by jimbxb** [comment]
I believe so. From memory they used to take 8mins and now I can wait double that. *grumble*

**Comment by pschachte** [comment]
I think this was fixed a while back.  Anyway, CI is working OK, and doesn't seem to take tooooo long.
