### ISSUE TITLE
Add support for anonymous functions as a syntax sugar for an anonymous proc

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#379]
Currently, the anonymous procedure syntax doesn't support "functions". For example, if we wanted to write a "successor" function, we would have to do:

```
{ @ + 1 = ?@ }
```

While this isn't too long, I propose an alternative syntax for a functional style:

```
@( @ + 1 )
```

I know what you're asking: why the leading `@`? The issue I foresee without the `@` or some other symbol to delineate that this is an anonymous proc is that there's no clear point wherein you can definitely say where the function starts or ends.

Consider this entirely made up, but somewhat sensible example where we drop the `@`:

```
map(compose(@ + 1, @ * 2), foo, ?bar)
```

While reading this, it's probably clear that we are composing two functions, but I'm not sure this is super easy to parse -- why are these `@`s special. 

Perhaps you could say that the fact they are separate arguments makes it easy to distinguish, but also consider this expression:

```
(@ + 1) <| (@ * 2)  # where `<|` is a composition operator
```

To the parser/normaliser, this looks no different to the `compose` example we had before. 

I hope I've been able to make my point clear why I think it's a lot easier if we use some special syntax for functions. It's a cost of up to 3 extra characters, and would help disambiguation. 

I suppose one other cost is that we'd now have to treat `@` as a prefix operator (which is already sort of parsed like it is). Grumble.

Edit: yes, I realise I could write something like `(@ + 1) * 2`. I wanted to keep the example simple

**Comment by pschachte** [comment]
Hmmm.  I wrote up a comment grudgingly agreeing with you, but then, the more I thought about it, the more I began to think that function composition, especially of unary functions, is special, and as your final comment observes, the basic @ notation already handles that quite well.  So do you have another example of the problem other than function composition?

**Comment by jimbxb** [comment]
Another issue I foresee is where "boundary" of the function lies. Say I had a function as follows:

```
def foo(x:int, y:int, ?z:int) {
   ?z = x+ y # doesn't matter, i just need an example 
}
```
Now for whatever reason I want to partially apply the function with the second argument fixed. I could do: `{ foo(@, 1, ?@) }`. With a functional notation, ideally you would be able to do `foo(@, 1)`. 

Suppose now I wanted to apply `foo` twice for whatever reason, ie `{ foo(foo(@, 1), 2, ?@) }`, which with a functional notation you would do `foo(foo(@, 1), 2)`. 

But now there's an issue. Which part is the function? Is it the whole expression or is it just the innermost `foo(@, 1)` as we had before.

I suppose we could just say that the `@`s in the functional notation can *only* be a "top level" argument to the function call... But this seems like it would get confusing to me.

**Comment by pschachte** [comment]
Yep, you're right, that's a big problem.  I can't think of anything better than your proposal, unless we try to use the type system to disambiguate.  In your example, unless `foo` is overloaded to allow a function as first argument,`foo(foo(@, 1), 2)` could only mean `@(foo(foo(@, 1), 2))`.

**Comment by jimbxb** [comment]
Type checking happens after flattening, but flattening is required before type checking to allow forr unique names for child/sibling `@`s... so I think we're in a bind here, unfortunately.

I'll progress with this proposed syntax when I find time.

**Comment by jimbxb** [comment]
Just to note my rough idea of how to support this:

- add `@` as a prefix operator in the parser, which requires modifications to how it is already parsed with anon parameters.
- handle flattening of anon functions. This would transform
`@( foo )` into the equivalent `{}{ foo = ?@ }`, which can then be flattened as per regular anonymous procs. One subtlety here is there can only be inputs in the original, which should be okay.
