### ISSUE TITLE
Upgrade LLVM version

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#380]
The curent version of llvm-hs only supports LLVM 9, yet there are versions that support higher versions of LLVM (see [llvm-hs](https://github.com/llvm-hs/llvm-hs)). Unfortunately, to my knowledge these aren't available on hackage, so we would have to pin our version down to a commit on the official GitHub. 

I suppose to suggest a version, we could target LLVM-12 as it is the default branch for the repo.

**Comment by pschachte** [comment]
Closing as this is now covered by issue #408.
