### ISSUE TITLE
Unbranching and Clause Generation causing variables to be undesirably reassigned to `undef`

### ISSUE THREAD

**Issue by wnats** [pschachte/wybe#398]
Unbranching may force variables to be reassigned (regardless of which branch is taken) even though no assignment occurs in one of the branches. This prompts the clause generation to reassign such variable with `undef`, overriding its original value.

For example, we expect the following code to print `false`, but it could print `true` instead.
```
def is_true(check:bool, ?res:bool) {
    ?res = false
    for ?i in 0..1 {
        if {
            check ::
                ?res = true
                break
        }
    }
}

!println(is_true(false))  # prints true in my PC, although it's conceptually an undef value
```
The logging after unbranching shows that `res` is initially assigned as `false`, which is correct. However, the last (continuation) proc call of `a.<0>is_true#cont#1(..., ?res)` overrides this initial value. The overriding occurs in a way that it is agnostic to the initial value. In the example code above (i.e. `is_true(false)`), no assignment occurs in the continuation proc, causing `res` to be reassigned to a variable that is undefined. This is further confirmed in the logging after compilation to LPVM, where `res:wybe.bool` is assigned to `undef:wybe.bool`.
```
======================================================================
AFTER UNBRANCHING:
...
is_true > (0 calls)
0: is_true(check:wybe.bool @a:1:13, ?res:wybe.bool @a:1:26):
    wybe.bool.<0>false(?tmp#0:wybe.bool @a:2:12)
    foreign llvm move(tmp#0:wybe.bool, ?res:wybe.bool @a:2:6)
    wybe.range.<0>..(0:wybe.int @a:3:15, 1:wybe.int @a:3:18, ?tmp#2:wybe.range @a:3:15)
    foreign llvm move(tmp#2:wybe.range, ?tmp#1:wybe.range)
    a.<0>is_true#cont#1(check:wybe.bool, tmp#1:wybe.range, ?res:wybe.bool @a:1:2

is_true#cont#1 > (0 calls)
0: is_true#cont#1(check:wybe.bool, tmp#1:wybe.range, ?res:wybe.bool @a:1:26):
    wybe.range.<0>[|](?i:wybe.int @a:3:10, ?tmp#1:wybe.range, tmp#1:wybe.range, ?tmp#4:wybe.bool)
    if {testbool tmp#4:wybe.bool::

        if {testbool check:wybe.bool::

            wybe.bool.<0>true(?tmp#3:wybe.bool @a:6:24)
            foreign llvm move(tmp#3:wybe.bool, ?res:wybe.bool @a:6:18)
        else::
            a.<0>is_true#cont#1(check:wybe.bool, tmp#1:wybe.range, ?res:wybe.bool @a:1:26)

        }
   condition -> {check::wybe.bool, i::wybe.int, res::wybe.bool, tmp#1::wybe.range, tmp#4::wybe.bool}
   then&else -> {check::wybe.bool, i::wybe.int, res::wybe.bool, tmp#1::wybe.range, tmp#3::wybe.bool, tmp#4::wybe.bool}
   resources -> {}
    else::

    }
   condition -> {check::wybe.bool, i::wybe.int, tmp#1::wybe.range, tmp#4::wybe.bool}
   then&else -> {check::wybe.bool, i::wybe.int, res::wybe.bool, tmp#1::wybe.range, tmp#3::wybe.bool, tmp#4::wybe.bool}
   resources -> {}
...
======================================================================
AFTER COMPILATION TO LPVM:
...
is_true > (1 calls)
0: a.is_true<0>
is_true(check##0:wybe.bool, ?res##1:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.bool.false<0>(?tmp#0##0:wybe.bool) #0 @a:2:12
    foreign llvm move(tmp#0##0:wybe.bool, ?res##0:wybe.bool) @a:2:6
    wybe.range...<0>(0:wybe.int, 1:wybe.int, ?tmp#2##0:wybe.range) #1 @a:3:15
    foreign llvm move(tmp#2##0:wybe.range, ?tmp#1##0:wybe.range) @a:3:5
    a.is_true#cont#1<0>(check##0:wybe.bool, tmp#1##0:wybe.range, ?res##1:wybe.bool) #2 @a:3:5


is_true#cont#1 > (2 calls)
0: a.is_true#cont#1<0>
is_true#cont#1(check##0:wybe.bool, tmp#1##0:wybe.range, ?res##0:wybe.bool)<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    wybe.range.[|]<0>(?i##0:wybe.int, ?tmp#1##1:wybe.range, tmp#1##0:wybe.range, ?tmp#4##0:wybe.bool) #0 @a:3:10
    case tmp#4##0:wybe.bool of
    0:
        foreign llvm move(undef:wybe.bool, ?res##0:wybe.bool)

    1:
        case check##0:wybe.bool of
        0:
            a.is_true#cont#1<0>(check##0:wybe.bool, tmp#1##1:wybe.range, ?res##0:wybe.bool) #2 @a:3:5

        1:
            wybe.bool.true<0>(?tmp#3##0:wybe.bool) #1 @a:6:24
            foreign llvm move(tmp#3##0:wybe.bool, ?res##0:wybe.bool) @a:6:18
```

**Comment by jimbxb** [comment]
The overriding here occurs because all output variables **must** be assigned a value in the clause they're an output of. Here, in the continuation, `res` is an output, which means it needs some value.

The compiler knows it has been assigned some value, `false`, in the root proc, but fails to carry this value forward when factoring the continuation. That is, as the output has been assigned already, that must be an input to the continuation. If this did occur, this `undef` assignment would be replaced with a no-op as the branch now has an assigned value for `res`.

I believe a fix for this would be to patch up the input parameters for continuations (again, sorry), adding in any output that's been assigned some value. This makes sense as the value is "used later", which is really what all of the continuation proc inputs should be, and the outputs being all outputs of the root proc.
