### ISSUE TITLE
Slight refactoring to how generators in `for` are flattened

### ISSUE THREAD

**Issue by wnats** [pschachte/wybe#406]
Currently, `for` statements in Wybe are converted from
```
for x in xs, y in ys {
    <stmts>
}
```
to
```
?#xs = xs
?#ys = ys
do {
    if { `[|]`(?x, ?#xs, #xs) ::
        if { `[|]`(?y, ?#ys, #ys) ::
            <stmts>
        | else :: break
        }
    | else :: break
    }
}
```
Instead of a series of `Cond` inside another `Cond`, would it be good to flatten it to a sequence of `Cond`s? i.e.
```
?#xs = xs
?#ys = ys
do {
    if { `[|]`(?x, ?#xs, #xs) :: pass | else :: break }  # while `[|]`(?x, ?#xs, #xs)
    if { `[|]`(?y, ?#ys, #ys) :: pass | else :: break }  # while `[|]`(?y, ?#ys, #ys)
    <stmts>
}
```
This has no semantic difference, although I just think it would look cleaner, especially if we were to implement more kind of generators

---
@pschachte This thought strikes me as I think of flattening an entity lookup/navigation statement (#125). I'm thinking of treating lookup/navigation as special generators, and if I also have a regular generator before that, I could just chuck the lookup/navigation statements after the regular generator. For instance, instead of 
```
do {
    if { `[|]`(?x, ?#xs, #xs) ::
        if { `[|]`(?y, ?#ys, #ys) ::
            <lookup/navigation ifs>
            <stmts>
        | else :: break
        }
    | else :: break
    }
}
```
we could have
```
do {
    if { `[|]`(?x, ?#xs, #xs) :: pass | else :: break }  # while `[|]`(?x, ?#xs, #xs)
    if { `[|]`(?y, ?#ys, #ys) :: pass | else :: break }  # while `[|]`(?y, ?#ys, #ys)
    <lookup/navigation ifs>
    <stmts>
}
```
I thought having a regular generator alongside a lookup/navigation could act as a counter, similar to `enumerate()` in Python. For example, if we'd like to limit the number of entities to be looked up.

**Comment by pschachte** [comment]
These ways of generating code actually aren't different, in the end.  LPVM is a clausal form, so there is never any code following a conditional, only code in each branch of the conditional.  Therefore, when the source code has code following a conditional, the unbrancher creates a proc holding the code that follows the conditional, and adds a call to this proc at the end of each branch.  In the case of a `break`, the code following the break is pruned away, leaving code that is identical to nesting the second conditional within the arm of the first one that doesn't contain a `break`.

**Comment by jimbxb** [comment]
Furthering the issue here with unbramching, having a series of sequential branches instead of nested branches generated here is going to create a lot of small, single-branch procs. As these prices have branches, they're likely never going to be marked for inlining. With this, the branches will be in separate procs, and will impede any intra-proc optimisations.
