### ISSUE TITLE
Foreign calls with Boolean outputs can't be de-reified into tests

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#412]
For example
```
pub def {test} lt(x:int, y:int) { foreign llvm icmp_slt(x,y) }
```
gets this error message
```
Foreign call 'icmp_slt' with arity 2; should be 3
```

**Comment by jimbxb** [comment]
I would think the call should be more like

```
foreign llvm {test} icmp_slt(x,y)
```

This way, we don't have to bake into the compiler which foreign calls are tests and not.

**Comment by pschachte** [comment]
If necessary, putting the `{test}` in there would be fine, but it shouldn't be necessary.  `foreign llvm icmp_slt(x,y)` should be considered to be a Boolean-valued expression (really i1, but that should be good enough), and when used as a statement in a test context, it should be de-reified into a test.  I suspect I'm de-reifying Wybe function calls, but not foreign function calls.

**Comment by pschachte** [comment]
I take it back.  The problem with my argument is that you can only know that the arity of the called instruction is one greater than the number of arguments supplied, and that the missing argument is a Boolean output, for llvm instructions.  For other foreign languages, we do no checking of arities and types.  So having the {test} flag indicate that there's one extra Boolean output argument, and that it should be immediately tested, is a more general facility.
