### ISSUE TITLE
Mutually imported modules with resources fail to compile

### ISSUE THREAD

**Issue by wnats** [pschachte/wybe#416]
`a.wybe`
```
use b
pub resource a_res:int = 42
```
`b.wybe`
```
use a
pub resource b_res:char = 'c'
```
Compiling `a.wybe` produces the following error message:
```
Error detected during type checking of module(s)
Input resource a_res not available at call to module top-level code
```
The exec module dump:
```
AFTER FLATTENING:
 Module 
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : 
  imports         : use a
                    use b
                    use command_line
                    use wybe
                    use wybe.array
                    use wybe.bool
                    use wybe.c_string
                    use wybe.char
                    use wybe.comparison
                    use wybe.control
                    use wybe.count
                    use wybe.float
                    use wybe.int
                    use wybe.io
                    use wybe.list
                    use wybe.machine_word
                    use wybe.memory_management
                    use wybe.phantom
                    use wybe.predicate
                    use wybe.range
                    use wybe.string
  resources       : 
  procs           : 

module top-level code > {terminal,impure} (0 calls)
0: () use command_line.argc, command_line.argv, ?command_line.exit_code:
    use a.a_res, b.b_res, command_line.arguments, command_line.command, wybe.io.io in
        !wybe.memory_management.
        !wybe.io.
        !command_line.
        !b.
        !a.
        foreign c {semipure,terminal} exit(exit_code:wybe.int)
    }

LLVM code       : None
```
The call to `!b.` needs `a_res` to be initialised, which happens on `!a.`. Ditto if we had called `!a.` first.

**Comment by jimbxb** [comment]
A good fix for this would be to house the resource initialisation before any mutually-recursive set of modules is called. 

I think the best place to put the resource initialisation for some SSC of modules is *just* before those modules' top-level code gets called in the executable main. We could also just hoist all resource initialisation to before any top-level code too, if that's easier.

**Comment by jimbxb** [comment]
After some more contemplation, I think that hoisting the raw initialisation code is going to get messy. Any temporary variables must be distinct, and that would require a renaming pass. Weaving in the init code is also messy.

Instead, what if we separate the top-level code from a module into its own procedure, `#init_resources`. This proc would have no arguments, only havin out-flowing resources for the given module, and would house the initialisation code. Then, at the executable main level, we can call these procedures for all modules that have them before the module's SCC's top-level code.

**Comment by pschachte** [comment]
Resource initialisations can in principle call any Wybe code, including code in modules used by that module.  If that imported code needs some kind of initialisation, then executing all resource initialisations before all other initialisations would cause problems.  In fact, in some cases it may be necessary to do some resource initialisation in the module initialisation code, such as when a single procedure call is used to get the initial values of a number of resources.  So I'd prefer to keep module initialisations to a single procedure, if we can.

In this case, there isn't actually a problem, since neither `a` nor `b`'s initialisation code actually uses the other's resource, so neither of them actually needs the other's resource as an input.  In general, a module's initialisation code may want to use another module's resource, but I don't think it makes sense for two modules' initialisations to depend on one another's resources.  So another fix for this problem would be for module initialisations only to list other modules' resources as input/outputs if they are not mutually dependent.

**Comment by jimbxb** [comment]
Yes, I agree that another fix would be to prune the input resources to only those that are imported and *not* in the module's SCC.

I'm not sure I understand the point on resource initialisation being required to be in the module -- the resource initialisation happens before any top-level code in the module (at least I thought), and any resource without initialisation code won't be in scope unless in a top-level `use` block

**Comment by pschachte** [comment]
My point was that sometimes resources can't be fully initialised in the resource declaration, and will be completed in the module top-level code.  For example, when multiple resources all need to be initialised together in a single statement.  Perhaps you want to initialise a bunch of separate resources based on a single procedure to parse the command line arguments, or maybe you have to execute some C initialisation code before you can initialise any of a few resources.  I don't think it's safe to assume that each resource can be fully initialised in the code that comes after the `=`, without executing other module top-level code.

You're right that the resource initialisations happen as the first part of a module's top-level code, and that resources without a specified initial value will not be in scope in any module's top-level code.  But you can specify some kind of dummy initial value (most types support something like that), and compute the real initial value in some more complex module initialisation code.
