### ISSUE TITLE
Compiler optimization give wrong LLVM output

### ISSUE THREAD

**Issue by 09milk** [pschachte/wybe#42]
Wybe code:
```
!println("hello world!")
```
correctly print out `hello world!`
while:
```
#test.wybe
def main() use io {
    !println("hello world!")
}
!main()
```
print out nothing.

`wybemk test.ll` give an almost empty text file:
```
; ModuleID = 'test'
source_filename = "....../test.wybe"
```

<br/>

`wybemk -V`:
```
wybemk 0.1 (git 40f3b16)
Built Wed Apr 22 13:37:07 AEST 2020
Using library directories:
    /usr/local/lib/wybe
```

**Comment by CaviarChen** [comment]
Had a quick look, the code got removed by this part of code.
https://github.com/pschachte/wybe/blob/ae5ba9986706049b9e04858c665aecb8035ba05c/src/Expansion.hs#L29-L57
But I am not familiar with this part.

**Comment by pschachte** [comment]
The bug here is that 'use io' needs to be 'use !io'.  The real bug is that the compiler allows you to throw away your changes to the io state.  That's a pretty deep bug, but I'll put in an issue for it.
