### ISSUE TITLE
The compiler allows changes to the io state to be thrown away

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#43]
In the following code:
```
def main use io {
    !println("hello world!")
}
!main
```
the compiler allows changes to the io state to be thrown away.  This happens because the `use` clause says `use io` instead of `use !io`.  Then the compiler sees that the main proc does not produce any output, so it optimises it away.

To fix this, we must introduce a restriction that io states cannot be copied -- we need linear types of some sort, which will be a significant effort.

**Comment by CaviarChen** [comment]
Just an idea, would it be possible to have some kind of warning to state that the `io` (the one after `!println`) is set but not used?
I always find this kind of warning useful in functional programming.  Especially in Haskell where the `let` is recursive(so we have names like x, x', x''), it's quite common for me to use the original value instead of the updated one by mistake.

**Comment by 09milk** [comment]
shouldn't the above code generate error instead of warning? `main` use `io` as input but does not state that `main` use `io` as output, while inside `main` `!println` use `io` as output

**Comment by pschachte** [comment]
This case should definitely be an error, but not for that reason.  If, for example, the resource being thrown away were an int, it would be fine.  You may well want to threat a value through a computation and throw it away at the end.  For example, you may traverse a tree collecting the labels and their integer position in the tree.  In that case, you would thread through an integer counter, increment it each time you collect a label, and throw away the counter at the end.  That's fine.

This case is an error because you're making a copy of the io state (which you can think of semantically as the state of the entire universe outside the computation), passing that state in to print out something, and then throwing away the new state of the universe and starting over again after the print from the previous state.  That's akin to going back in time and not doing the print.  And of course, that's what the Wybe compiler actually implemented in this example.

So what's needed is a way to mark a type as being linear, which means that it's not permitted to copy or alias it.  Ie, every time you pass it as an argument in a call, it is the last use of it in that procedure body.  Any violation of this would be a compiler error.  Then io would be one such type.  It could also be used for types where you want to be sure that structure changes are always destructive.

**Comment by pschachte** [comment]
Fixed by #222
