### ISSUE TITLE
Generalise string interpolation to allow use of higher arity versions of fmt

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#456]
There should be a string interpolation syntax that allows multiple arguments to be passed to the fmt function.

See also issues #454 and #455.  This should capitalise on the former and should not interfere with the latter.

**Comment by jimbxb** [comment]
At the moment, wrapping an expression in parens does nothing to what is formatted. I.e., `"...$(x)..." = `"...$x..."`. 

This to me looks a lot like a call to a function (`fmt`) with a single argument. So why not allow for extra arguments to be passed by comma-separating them within the parens, which generalises fairly well if multiple args are required.

For example, with `x:float`:

```
"...$(x)..." = "...$(fmt(x))..."
"...$(x,2)..." = "...$(fmt(x,"2"))..." # x with 2 points of precision
"...$(x,+03)..." = "...$(fmt(x,"+03"))..." # x with 3 points of precision, zero padded, and signed
```

I think we'd probably need to make the following arguments strings. We *could* interpret some as ints (if they're all numeric), but we would lose some information (leading zeros). Fwiw, I believe this is in essence how Python handles this, albeit with a different syntax.

**Comment by pschachte** [comment]
I agree, allowing commas inside the `$(...)` interpolations makes perfect sense.

I'm less enthusiastic about using a string to encode multiple formatting attributes, like explicit sign, 0 filling, and field width.  It seems nicer to me to make these separate arguments.  After #41 is implemented, optional arguments would be a good way to accept default values, to avoid having to specify too much detail.  Particularly if named arguments are supported, and doubly so if Boolean optional arguments can be specified with the argument name but omitting the "=true", so you could write something like "...$(x, signed, precision=3)..." to call fmt(x:float, precision:int, signed:bool).

**Comment by jimbxb** [comment]
Ah yes, optional arguments make perfect sense!
