### ISSUE TITLE
Optimiser sometimes falsely allocates the same memory address

### ISSUE THREAD

**Issue by wnats** [pschachte/wybe#464]
`a.wybe`
```
use foo

resource a:foo(int) = foo
resource b:foo(char) = foo

set(!a, 97)

!println(get(b))
```

`foo.wybe`
```
pub def foo:_(V) = bar(empty_container)

pub def get(foo:_(V), ?val:V) {
    foreign lpvm access(foo^raw_data, 0, word_size_bytes, 0, ?val)
}

pub def set(!foo:_(V), val:V) {
    foreign lpvm mutate(foo^raw_data, ?foo^raw_data, 0, 1, word_size_bytes,
                        0, val)
}

constructor (V) bar(raw_data:raw_array)

def {noinline} empty_container:raw_array = res where {
    foreign lpvm alloc(word_size_bytes, ?res)
    foreign lpvm mutate(res, ?res, 0, 1, word_size_bytes, 0,
                        foreign lpvm cast(65):V)
}
```

Compiling and running `a.wybe` prints out `a` (ascii 97) when `A` (ascii 65) is expected. In the final dump, `a` and `b` are assigned the same memory address.

Some things required to reproduce this issue:
* `foo` has to be generic
* `empty_container` has to be `noinline`
* `a` and `b` have to be resources
* `foreign lpvm mutate` has to have its destructive flag on
* If the type of `foo` is an address, i.e. its field sizes sum up greater than 64 bits, proc `foo` has to be declared as `inline`

**Comment by jimbxb** [comment]
This is an interesting bug. 

* I wonder why they both have to be resources? I assume it's because there's some inlining that doesn't occur with resources
* Do you know which part of the memory is shared? Is it the `raw_array` or the `foo`?

**Comment by wnats** [comment]
> I wonder why they both have to be resources? I assume it's because there's some inlining that doesn't occur with resources
I have not investigated much, but I think so, since resources are initialised in the main proc.

> Do you know which part of the memory is shared? Is it the `raw_array` or the `foo`? I suppose whichever it is is allocated twice before optimisation, and then later due to common-subexpression elimination, one of them is eliminated and the other is reused - this then means the mutations are mutating the same memory
The `raw_array` I believe. If I add an extra field to the `bar` constructor (in this case I added a `bool`), the following is generated in the main exe proc:
```
    foo.empty_container<0>(?tmp#15##0:wybe.array.raw_array) #6 @a:3:23
    foreign lpvm alloc(16:wybe.int, ?tmp#16##0:foo(V)) @a:3:23
    foreign lpvm mutate(~tmp#16##0:foo(V), ?tmp#17##0:foo(V), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 1:wybe.bool) @a:3:23
    foreign lpvm mutate(~tmp#17##0:foo(V), ?tmp#1##0:foo(wybe.int), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, tmp#15##0:wybe.array.raw_array) @a:3:23
    foreign lpvm store(~tmp#1##0:foo(wybe.int), <<a.a>>:foo(wybe.int)) @a:3:1
    foreign lpvm alloc(16:wybe.int, ?tmp#19##0:foo(V)) @a:4:24
    foreign lpvm mutate(~tmp#19##0:foo(V), ?tmp#20##0:foo(V), 0:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, 1:wybe.bool) @a:4:24
    foreign lpvm mutate(~tmp#20##0:foo(V), ?tmp#2##0:foo(wybe.char), 8:wybe.int, 1:wybe.int, 16:wybe.int, 0:wybe.int, ~tmp#15##0:wybe.array.raw_array) @a:4:24
    foreign lpvm store(~tmp#2##0:foo(wybe.char), <<a.b>>:foo(wybe.char)) @a:4:1
    a.<0><{<<a.a>>, <<a.b>>, <<wybe.io.io>>}; {<<a.a>>, <<wybe.io.io>>}; {}> #5
```

> That makes me wonder: does the 1 flag have to be set?
Yes.

**Comment by jimbxb** [comment]
I see. So because `empty_container` is marked as `noinline`, the result of that is reused. That makes sense because it's `pure`. 

That would imply that the mutation that occurs in `set` is really to blame - it's not pure, and so the mutation shouldn't have the `1` flag set. `set` doesn't own the memory (i.e it was passed in through a parameter, so mutating it can only be guaranteed as safe if it's unalised (I believe multispecz could generate a specialisation that can do this, though)

**Comment by pschachte** [comment]
I think the problem occurs earlier than that.  It sounds like the problem here is that a and b both hold the same value (they're aliases).  I think the right fix is to make foo impure, or thread the `io` state through it, and precede the calls to it with a `!` to make clear that a `~=` b (ie, a and b hold different boxes).

**Comment by jimbxb** [comment]
i think you should also make `set` at least `semipure`.

**Comment by wnats** [comment]
Thanks @jimbxb and @pschachte. I'll close this issue since no change is applicable to the repo.
