### ISSUE TITLE
Nested loops are optimized away

### ISSUE THREAD

**Issue by rudolphalmeida** [pschachte/wybe#63]
[loop.wybe.txt](https://github.com/pschachte/wybe/files/4762312/loop.wybe.txt)

A single `do` loop like the one in the above attached file executes as expected.

[nested_loop.wybe.txt](https://github.com/pschachte/wybe/files/4762322/nested_loop.wybe.txt)

However, using a nested `do` or `for` loop optimizes the inner loop away and inlines only a single iteration of the outer loop.
Expected output:
```
Outer
Inner
Inner
...
```

Actual output:

```
Outer

```

The inner loop is optimized away somewhere between `Clause.hs` and `Expansion.hs`.

**Comment by pschachte** [comment]
Fixed by #89
